# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_administrator_bill_menu_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='dish_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurant.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(to='restaurant.Menu'),
        ),
    ]
